// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Nav("home").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <main><section class=\"relative overflow-hidden bg-[radial-gradient(circle_at_80%_10%,rgba(31,78,95,0.14),transparent_30%),linear-gradient(180deg,#FAFAF8,#F3F1EC)]\"><div class=\"mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[1.05fr_0.95fr] lg:px-8 lg:py-32\"><div><p class=\"eyebrow\">Structured Stellar data</p><h1 class=\"mt-5 text-5xl font-semibold tracking-[-0.055em] md:text-7xl\">Data infrastructure for Stellar and Soroban.</h1><p class=\"mt-7 max-w-2xl text-xl leading-8 text-obsrvr-muted\">Obsrvr turns Stellar ledger activity into queryable products: compliance monitoring, APIs, and Prism block explorer experiences.</p><div class=\"mt-9 flex flex-wrap gap-3\"><a href=\"/compliance\" class=\"btn-primary\">Explore Compliance</a><a href=\"#platform\" class=\"btn-secondary\">View platform</a></div></div><div class=\"rounded-[2rem] border border-black/10 bg-white p-5 shadow-2xl shadow-black/10\"><div class=\"rounded-3xl bg-obsrvr-ink p-6 text-white\"><div class=\"flex items-center justify-between\"><span class=\"font-mono text-xs text-white/50\">ledger pipeline</span><span class=\"rounded-full bg-emerald-400/20 px-3 py-1 font-mono text-xs text-emerald-200\">live</span></div><div class=\"mt-8 grid gap-3\"><div class=\"rounded-2xl bg-white/10 p-4\"><span class=\"text-sm text-white/60\">Ingest</span><div class=\"mt-2 text-2xl font-semibold\">55.8M ledgers</div></div><div class=\"rounded-2xl bg-white/10 p-4\"><span class=\"text-sm text-white/60\">Normalize</span><div class=\"mt-2 text-2xl font-semibold\">Stellar + Soroban</div></div><div class=\"rounded-2xl bg-white/10 p-4\"><span class=\"text-sm text-white/60\">Serve</span><div class=\"mt-2 text-2xl font-semibold\">SQL · APIs · Apps</div></div></div></div></div></div></section><section id=\"platform\" class=\"mx-auto max-w-7xl px-5 py-20 lg:px-8\"><div class=\"grid gap-5 md:grid-cols-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Step("01", "Compliance", "Stablecoin flow intelligence for AML workflows on Stellar.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Step("02", "APIs", "Structured data via REST and direct analytical access.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Step("03", "Prism", "A Soroban-first block explorer powered by Obsrvr data.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Footer().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Obsrvr — Structured data infrastructure for Stellar and Soroban").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
